const SYSTEM_CHECK_LOGIN = "SYSTEM_CHECK_LOGIN";
const SYSTEM_PATH_RECORDS = "SYSTEM_PATH_RECORDS";
const SYSTEM_LAST_LIST_STAT = "SYSTEM_LAST_LIST_STAT";
const constant = {
  SYSTEM_CHECK_LOGIN,
  SYSTEM_PATH_RECORDS,
  SYSTEM_LAST_LIST_STAT
};

export default constant;
